### ISSUE TITLE
'FFMpegWriter' object has no attribute '_proc' errors

### ISSUE THREAD

**Issue by fpx006** [cwlroda/falldetection_openpifpaf#18]
I got this error when I use mp4 files, but in RTSP stream it works.

>c:\python38\python.exe -m openpifpaf.video --source D:\202111125_101010_1_test_1.mp4 --video-output "D:\test1.mp4"
2021-12-07 10:39:22,433 [INFO]: MainProcess video.py(cli:112) >> neural network device: cuda
2021-12-07 10:39:23,609 [INFO]: MainProcess animation_frame.py(__init__:47) >> video output = D:\test1.mp4
Exception ignored in: <generator object AnimationFrame.iter at 0x00000000B316ADD0>
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\openpifpaf\show\animation_frame.py", line 89, in iter
    self.video_writer.finish()
  File "c:\python38\lib\site-packages\matplotlib\animation.py", line 344, in finish
    self._cleanup()  # Inline _cleanup() once cleanup() is removed.
  File "c:\python38\lib\site-packages\matplotlib\animation.py", line 362, in _cleanup
    out, err = self._proc.communicate()
AttributeError: 'FFMpegWriter' object has no attribute '_proc'

**Comment by fpx006** [comment]
I write source file in config.xml, the error fixed !
