### ISSUE TITLE
some issue to run on webcam

### ISSUE THREAD

**Issue by alighofrani95** [cwlroda/falldetection_openpifpaf#2]
thanks a lot for this great and useful repo...

I followed step by step but I faced with the error below:

python3 -m openpifpaf.video --source 0 --show

Traceback (most recent call last):
  File "/home/ali/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ali/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ali/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/site-packages/openpifpaf/video.py", line 303, in <module>
    main()
  File "/home/ali/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/site-packages/openpifpaf/video.py", line 278, in main
    inference(args, streamer)
  File "/home/ali/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/site-packages/openpifpaf/video.py", line 185, in inference
    if RTSPURL.startswith('rtsp'):
AttributeError: 'int' object has no attribute 'startswith'

**Comment by tim120526** [comment]
> thanks a lot for this great and useful repo...
> 
> I followed step by step but I faced with the error below:
> 
> python3 -m openpifpaf.video --source 0 --show
> 
> Traceback (most recent call last):
> File "/home/ali/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/home/ali/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/home/ali/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/site-packages/openpifpaf/video.py", line 303, in
> main()
> File "/home/ali/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/site-packages/openpifpaf/video.py", line 278, in main
> inference(args, streamer)
> File "/home/ali/anaconda3/envs/falldetection_openpifpaf/lib/python3.7/site-packages/openpifpaf/video.py", line 185, in inference
> if RTSPURL.startswith('rtsp'):
> AttributeError: 'int' object has no attribute 'startswith'

hey,guy. have u solved it ?

**Comment by robbiwu** [comment]
I had this problem, I recopied the git folder over to the correct folder. Mine was Windows 10 so its not 1 for 1. Works

**Comment by alighofrani95** [comment]
> I had this problem, I recopied the git folder over to the correct folder. Mine was Windows 10 so its not 1 for 1. Works

Could you please explain more where the exactly you copied the repo?

**Comment by robbiwu** [comment]
My working dir was /windows/user/rober/

The git dir -> C:\Users\rober\falldetection_openpifpaf
To C:\Users\rober\anaconda3\envs\falldetection_openpifpaf\Lib\site-packages\openpifpaf

Then make sure you modify the config.xml in the second folder and not the env root 😊

Hope this helps 😊

Robbi.

**Comment by robbiwu** [comment]
make sure you modify your config.xml (RTSPURL)

**Comment by MilkTeaMix** [comment]
@robbiwu can you explain be about to modify config.xml (RTSPURL).

**Comment by robbiwu** [comment]
@MilkTeaMix - Hello. Ok your problem is the default cam index for opencv and/or possibly your config.xml

Change your config.xml
id and RTSPURL to "webcam"

Set scale accordingly and then modify video.py line 163 from 

 capture = cv2.VideoCapture(-1) to  capture = cv2.VideoCapture(0)

then run as python -m openpifpaf.video --show
Happy falling :)

**Comment by MilkTeaMix** [comment]
Thank you so much @robbiwu . next quetion can i get the fallcount value or show in figure.

**Comment by theyoungghost** [comment]
@cwlroda 
@robbiwu
Hi，I encountered a problem while running this project, Could you help me ？ please.
I try to run this project in Window10.
When I try to run 'python -m openpifpaf.video --show'.
This problem arises: ModuleNotFoundError: No module named 'openpifpaf.functional'
![image](https://user-images.githubusercontent.com/95341128/155870989-cbd2e88a-d6df-4e61-aa98-008497b6b57d.png)
And then I find the functional module most possible is the file named functional.c
![image](https://user-images.githubusercontent.com/95341128/155871090-c09da1d6-aaae-430c-9ba1-a209808e1823.png)
![image](https://user-images.githubusercontent.com/95341128/155871102-39ad02cd-c34b-41c1-b824-19b9ca9f245e.png)
Because I find the same name func in the functional.c
![image](https://user-images.githubusercontent.com/95341128/155871141-bc4fdf7d-1c1e-4708-9050-89ee6a62c863.png)
![image](https://user-images.githubusercontent.com/95341128/155871149-3b8a5c78-7784-45e4-8967-7530e7979dc3.png)
That‘s all, Please help me！Thanks

**Comment by vaibhav-OG** [comment]
@theyoungghost find any solution?
